package nlp.tweetanalyzers;

import edu.stanford.nlp.pipeline.CoreDocument;
import edu.stanford.nlp.pipeline.CoreSentence;
import edu.stanford.nlp.pipeline.StanfordCoreNLP;
import nlp.AnalyzedTweet;
import nlp.SanitizedTweet;

import java.util.LinkedList;
import java.util.List;
import java.util.Properties;

public class StandfordNLPTweetAnalyzer implements OverallSentimentAnalyzer, SentenceSentimentAnalyzer {

    private StanfordCoreNLP pipeline;
    private Properties properties;

    private static StandfordNLPTweetAnalyzer standfordNLPTweetAnalyzer = null;

    /**
     * Singleton design pattern
     * @return
     */
    public static StandfordNLPTweetAnalyzer getInstance(){
        System.out.println("get instance");
        if(standfordNLPTweetAnalyzer == null)
            standfordNLPTweetAnalyzer = new StandfordNLPTweetAnalyzer();
        return standfordNLPTweetAnalyzer;
    }

    private StandfordNLPTweetAnalyzer(){
        properties = new Properties();
        properties.setProperty("annotators", "tokenize,ssplit,pos,lemma,ner,parse,depparse, sentiment");
        properties.setProperty("ner.useSUTime", "false");
        pipeline = new StanfordCoreNLP(properties);
    }
    @Override
    public AnalyzedTweet analyzeSanitizedTweetSentiment(SanitizedTweet sanitizedTweet) {
        AnalyzedTweet analyzedTweet = new AnalyzedTweet(sanitizedTweet);
        CoreDocument document = new CoreDocument(analyzedTweet.getSanitizedText());
        pipeline.annotate(document);

        List<CoreSentence> sentences = document.sentences();
        int len = sentences.size();

        String[] strSentences = new String[len];
        int[] sentenceSentiments = new int[len];

        for (int i = 0; i < len; i++)
        {
            strSentences[i] = sentences.get(i).text();

            String sentiment = sentences.get(i).sentiment();
            sentenceSentiments[i] = stanfordNLPSentimentStringToSentimentInteger(sentiment);
        }
        analyzedTweet.setSentences(strSentences);
        analyzedTweet.setSentenceSentiments(sentenceSentiments);
        analyzedTweet.setOverallSentiment(analyzeOverallTweetSentiment(analyzedTweet));
        analyzedTweet.setAnalysisAuthorClassName(getAnalyzerClassName());
        return analyzedTweet;
    }

    /**
     * Given a sentiment string generated by analyzing something in stanford nlp library
     * We output the correct integer that will be mapped to the correct sentiment with in this analzyedtweet class.
     *
     * @param sentiment - generated by nlp
     * @return Integer.MIN_VALUE if sentiment unsupported, other wise one of the sentiment constants
     */
    private static int stanfordNLPSentimentStringToSentimentInteger(String sentiment){
        sentiment = sentiment.trim().toLowerCase();
        switch (sentiment)
        {
            case "very negative" :
                return AnalyzedTweet.VERY_NEGATIVE_SENTIMENT;
            case "negative" :
                return AnalyzedTweet.NEGATIVE_SENTIMENT;
            case "neutral" :
                return AnalyzedTweet.NEUTRAL_SENTIMENT;
            case "positive" :
                return AnalyzedTweet.POSITIVE_SENTIMENT;
            case "very positive" :
                return AnalyzedTweet.VERY_POSITIVE_SENTIMENT;
        }
        return Integer.MIN_VALUE;
    }

    @Override
    public List<AnalyzedTweet> analyzeSanitizedTweetsSentiment(List<SanitizedTweet> sanitizedTweets) {
        List<AnalyzedTweet> analyzedTweets = new LinkedList<>();
        for(SanitizedTweet sanitizedTweet : sanitizedTweets){
            AnalyzedTweet analyzedTweet = analyzeSanitizedTweetSentiment(sanitizedTweet);
            analyzedTweets.add(analyzedTweet);
        }
        return analyzedTweets;
    }

    /**
     * Stanford nlp only does sentiment on sentences so we must determine the over sentiment of the tweet based on the
     * sentiment of each sentence.
     *
     * @param sanitizedTweet
     * @return
     */
    public int analyzeOverallTweetSentiment(SanitizedTweet sanitizedTweet) {
        AnalyzedTweet analyzedTweet = null;

        boolean needToRunThroughPipeline = true;
        if(sanitizedTweet instanceof AnalyzedTweet)
        {
            analyzedTweet = (AnalyzedTweet) sanitizedTweet;

            //determine if have not  analyzed this with the pipeline
            if(analyzedTweet.getSentenceSentiments() != null){
                needToRunThroughPipeline = false;
            }
        }

        if(needToRunThroughPipeline)
            analyzedTweet = analyzeSanitizedTweetSentiment(sanitizedTweet);

        int[] sentenceSentiments = analyzedTweet.getSentenceSentiments();
        int overallSentiment = 0;

        int totalPositive = 0;
        int totalVeryPostive = 0;
        int totalNegative = 0;
        int totalVeryNegative = 0;
        int totalNeutral = 0;
        for(int i = 0; i < sentenceSentiments.length; i++)
        {
            switch (sentenceSentiments[i])
            {
                case AnalyzedTweet.VERY_NEGATIVE_SENTIMENT :
                    totalVeryNegative++;
                    break;
                case AnalyzedTweet.NEGATIVE_SENTIMENT :
                    totalNegative++;
                    break;
                case AnalyzedTweet.NEUTRAL_SENTIMENT:
                    totalNeutral++;
                    break;
                case AnalyzedTweet.POSITIVE_SENTIMENT:
                    totalPositive++;
                    break;
                case AnalyzedTweet.VERY_POSITIVE_SENTIMENT:
                    totalVeryPostive++;
                    break;
            }
        }

        int sum = (totalNegative*-1) + (totalVeryNegative*-2) + (totalNeutral*0) + (totalPositive*1) + (totalVeryNegative*2);

        if(sum < 0)
            overallSentiment = AnalyzedTweet.NEGATIVE_SENTIMENT;
        else if(0 < sum)
            overallSentiment = AnalyzedTweet.POSITIVE_SENTIMENT;
        else if (sum == 0)
            overallSentiment = AnalyzedTweet.NEUTRAL_SENTIMENT;

        return overallSentiment;
    }

    /**
     * Returns the name of the analyzed classname use this to sign each tweet you analyze with the name of your class.
     * i.e analyzedTweet.setAnalysisAuthorClassName(this.getClass().getName())
     *
     * @return
     */
    @Override
    public String getAnalyzerClassName() {
        return this.getClass().getName();
    }
}
